name: React Native Test

on:
  push:
    branches:
      - main  # Adjust this to your main branch name
  pull_request:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the version based on your project requirements

      - name: Install dependencies
        run: npm install

      - name: Build Android
        run: npx react-native run-android --no-jetifier --no-hermes

      - name: Build iOS
        run: npx react-native run-ios --no-jetifier --no-hermes

      - name: Run tests
        run: npm test  # Replace with your test command if you have a different setup
